version: "2"
services:
  bankifitest:
    image: bankifitest
    ports:
      - "8080:8080"
      - "9095:9095"

  prom:
    image: prom/prometheus
    volumes:
      - ./monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    depends_on:
      - bankifitest

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prom
    volumes:
      - ./monitor/grafana:/var/lib/grafana